#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

app_version() {
 echo "2.1.1"
}
if [ -z "$@" ] ; then
  log "-i" "entrypoint" "default"
  /usr/bin/pgrep yarn > /dev/null
  TEST=$?
  if [ $TEST -eq 1 ] ; then
   log "-i" "entrypoint" "Blocking application - gitea($(app_version))"
    /usr/bin/yarn start
  fi
  return 1
else
 log "-i" "entrypoint" "Override default($ENTRYPOINT_PARAMS)"
 log "-i" "entrypoint" "Detatched application - gitea($(app_version))"
 /usr/bin/yarn start >> /mnt/volumes/container/_log 2>&1 &
 return 0
fi



